# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

 desc "Build Cleaning"
  lane :cleanAndBuild do
  clear_derived_data
end
  
  desc "Install cocoapods"
lane :install_pods do
  cocoapods(
      clean: true,
      use_bundle_exec: false
)
end

  desc "Sharing Build"
  lane :uploadToDiawi do |values|
    diawi(token: values[:token], file: values[:file])
  end

  desc "Create ipa"
  	lane :build do
      app_identifier = "com.tspl.cross.concentrixone"
      configuration = "development"

  app_store_connect_api_key(
    key_id: "4L52HUVVC4",
    issuer_id: "69a6de90-9db5-47e3-e053-5b8c7c11a4d1",
    key_filepath: "./AuthKey_4L52HUVVC4.p8",
    duration: 1200,
    in_house: false # optional but may be required if using match/sigh
  )
   # Build Cleaning
      #cleanAndBuild
   # Pod install
      #install_pods
     match(type: "development", readonly: true, force_for_new_devices: true, git_private_key: "SHA256:s6KK3OMxbyE+flQVVi0eSaXRWY9fbIiTYuOoW0ZPJZk")
   # Increases the build number by 1
	   increment_build_number
   # Creates a signed file
	   gym( export_method: configuration, clean: true)
   # Build Sharing
     uploadToDiawi token: "yyUqLNEoWKnkeJeGmSC45GH2Gkc7U9sLV3Vv7ATiLI", file: "./fastlane/builds/FastLaneExample.ipa"
 end

end


